### Integrantes das questões em grupo $(1$ & $3)$:

###### Filipe Pierri de Mendonça Nobre - $118033026$

###### Thales Monteiro Pierini Macena - $116194266$

###### Daniel Pinheiro Rodrigues - $118019420$

1-

In [2]:
function RESOLVE_DIAGONAL(matriz, vetor) #passa matriz nxn e vetor
  lin, col = size(matriz) #queremos só o num de linhas, o num de colunas não vai ser usado

  resultado = zeros(lin) #preenchemos um vetor com tamanho igual ao número de linhas preenchido por zeros

  for i=1:lin
    resultado[i] = vetor[i] / matriz[i, i] #dividindo v[i] por m[i][i] (o valor na diagonal correspondente a posição i) e armazenando no vetor resultado em [1]
  end

  return resultado
end

RESOLVE_DIAGONAL (generic function with 1 method)

In [3]:
matriz1 = [1 2 3; 4 5 6; 7 8 9]
vetor1 = [1; 1; 1]

matriz2 = [1 1 1; 1 1 1; 1 1 1]
vetor2 = [1; 2; 3]

matriz3 = [1 2 3; 4 5 6; 7 8 9]
vetor3 = [1; 5; 9]

print("Diagonal 1: ")
print(RESOLVE_DIAGONAL(matriz1, vetor1))
print("\n\n")
print("Diagonal 2: ")
print(RESOLVE_DIAGONAL(matriz2, vetor2))
print("\n\n")
print("Diagonal 3: ")
print(RESOLVE_DIAGONAL(matriz3, vetor3))

Diagonal 1: [1.0, 0.2, 0.1111111111111111]

Diagonal 2: [1.0, 2.0, 3.0]

Diagonal 3: [1.0, 1.0, 1.0]

In [4]:
function RESOLVE_TRIANNGULAR_SUPERIOR(matriz, vetor) #passa matriz nxn e vetor
  lin, col = size(matriz) #queremos só o num de linhas, o num de colunas não vai ser usado
  resultado = zeros(lin) #preenchemos um vetor com tamanho igual ao número de linhas preenchido por zeros

  for i=lin:-1:1  #for decrescente, para começar pelo x[n][n]
    if i==lin
      resultado[i] = vetor[i] / matriz[i,i]  #dividindo v[i] por m[i][i] (o valor na diagonal correspondente a posição i) e armazenando no vetor resultado em [i]
    else #para os que não são x[n][n]
      aux = vetor[i] #recebe valor de v[i]
      for j=lin:-1:i+1 #for decrescente para podermos calcular o R(n)
        aux -= matriz[i,j] * resultado[j]
      end
      aux = aux / matriz[i,i]
      resultado[i] = aux
    end
  end

  return resultado
end

RESOLVE_TRIANNGULAR_SUPERIOR (generic function with 1 method)

In [5]:
matriz1 = [1 1 1; 0 1 1; 0 0 1]
vetor1 = [9; 5; 3]

matriz2 = [2 2 2; 0 2 2; 0 0 2]
vetor2 = [18; 10; 6]

matriz3 = [3 3 3; 0 3 3; 0 0 3]
vetor3 = [27; 15; 9]

print("Resultado 1: ")
print(RESOLVE_TRIANNGULAR_SUPERIOR(matriz1, vetor1))
print("\n\n")
print("Resultado 2: ")
print(RESOLVE_TRIANNGULAR_SUPERIOR(matriz2, vetor2))
print("\n\n")
print("Resultado 3: ")
print(RESOLVE_TRIANNGULAR_SUPERIOR(matriz3, vetor3))

Resultado 1: [4.0, 2.0, 3.0]

Resultado 2: [4.0, 2.0, 3.0]

Resultado 3: [4.0, 2.0, 3.0]

In [6]:
function RESOLVE_TRIANNGULAR_INFERIOR(matriz, vetor) #passa matriz nxn e vetor
  lin, col = size(matriz)  #queremos só o num de linhas, o num de colunas não vai ser usado
  resultado = zeros(lin) #preenchemos um vetor com tamanho igual ao número de linhas preenchido por zeros

  for i=1:lin #for crescente, para começar pelo x[1][1]
    if i==1
      resultado[i] = vetor[i] / matriz[i,i] #dividindo v[i] por m[i][i] (o valor na diagonal correspondente a posição i) e armazenando no vetor resultado em [i]
    else #para os que não são x[1][1]
      aux = vetor[i] #recebe valor de v[i]
      for j=1:i-1 #for crescente para podermos calcular o R(n)
        aux -= matriz[i,j] * resultado[j]
      end
      aux = aux / matriz[i,i]
      resultado[i] = aux
    end
  end

  return resultado
end

RESOLVE_TRIANNGULAR_INFERIOR (generic function with 1 method)

In [7]:
matriz1 = [1 0 0; 1 1 0; 1 1 1]
vetor1 = [9; 5; 3]

matriz2 = [2 0 0; 2 2 0; 2 2 2]
vetor2 = [18; 10; 6]

matriz3 = [3 0 0; 3 3 0; 3 3 3]
vetor3 = [27; 15; 9]

print("Resultado 1: ")
print(RESOLVE_TRIANNGULAR_INFERIOR(matriz1, vetor1))
print("\n\n")
print("Resultado 2: ")
print(RESOLVE_TRIANNGULAR_INFERIOR(matriz2, vetor2))
print("\n\n")
print("Resultado 3: ")
print(RESOLVE_TRIANNGULAR_INFERIOR(matriz3, vetor3))

Resultado 1: [9.0, -4.0, -2.0]

Resultado 2: [9.0, -4.0, -2.0]

Resultado 3: [9.0, -4.0, -2.0]

In [8]:
function DECOMPOSICAO_LU(matrix) #passa matriz nxn (por favor, use floats)
    n = size(matrix, 1)      # tamanho da matriz nXn
    auxMatrix = copy(matrix) # matriz que será subtraída a cada loop até ser uma matriz de zeros
    L = zeros(n, n)          # L como matriz zerada
    U = zeros(n, n)          # U como matriz zerada
    
    # Iterando pela diagonal
    for d = 1:n
        # Pega o número da diagonal para dividirmos a coluna escolhida
        pivot = auxMatrix[d, d]
        
        # Coloca diretamente em L e U o produto externo
        # ou seja, colocará o vetor coluna em L e o vetor linha em U
        # porque o produto de uma matriz é equivalente a soma dos produtos externos dos vetores de linha e coluna
        for i = d:n
            L[i, d] = auxMatrix[i, d]/pivot # vetor de coluna
            U[d, i] = auxMatrix[d, i]       # multiplos do vetor de coluna
        end
        
        # Realiza a subtração
        for col = d:n
            for row = d:n
                auxMatrix[row, col] -= L[row, d]*U[d, col]
            end
        end
    end
    
    return (L, U)
end

DECOMPOSICAO_LU (generic function with 1 method)

In [9]:
# Matriz de floats, para não dar erro de divisão por fração
matriz1 = [1.0 2.0 3.0; 0.0 4.0 5.0; 1.0 0.0 6.0]
matriz2 = [2.0 1.0 0.0; 0.0 1.0 0.0; 1.0 2.0 1.0]
matriz3 = [1.0 -2.0 5.0; 0.0 1.0 -4.0; 0.0 0.0 1.0]

print("LU 1: ")
print(DECOMPOSICAO_LU(matriz1))
print("\n\n")
print("LU 2: ")
print(DECOMPOSICAO_LU(matriz2))
print("\n\n")
print("LU 3: ")
print(DECOMPOSICAO_LU(matriz3))

LU 1: ([1.0 0.0 0.0; 0.0 1.0 0.0; 1.0 -0.5 1.0], [1.0 2.0 3.0; 0.0 4.0 5.0; 0.0 0.0 5.5])

LU 2: ([1.0 0.0 0.0; 0.0 1.0 0.0; 0.5 1.5 1.0], [2.0 1.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0])

LU 3: ([1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0], [1.0 -2.0 5.0; 0.0 1.0 -4.0; 0.0 0.0 1.0])

O algoritmo de calcular a inversa é O(n^3). Para resolver matriz triangular é O(n^2) e para resolver pra cada coluna da matriz é O(n). Logo é O(n^3)

In [10]:
function INVERSA(matriz) # Função recebe como entrada uma matriz e retorna sua inversa
  lin, col = size(matriz) # Pega os valores da matriz

  L, U = DECOMPOSICAO_LU(matriz) # Chama a função DECOMPOSICAO_LU para obter L e U

  IA = zeros(lin, col) # Define a inversa da matriz de entrada como uma matriz de zeros

  for i = 1:col # Para uma matriz identidade de tamanho nxn
    # Defino a coluna i da matriz identidade
    ei = zeros(col)
    ei[i] = 1

    # z = (Ua)
    # Resolvo o sistema Lz = ei
    z = RESOLVE_TRIANNGULAR_INFERIOR(L, ei)

    # Resolvo o sistema Ua = z
    ai = RESOLVE_TRIANNGULAR_SUPERIOR(U, z)

    # Coloca as colunas da matriz Inversa de A  
    for x = 1:length(ai)
      IA[x, i] = ai[x]
    end
  end

  # Retorna a matriz inversa
  return IA
end

INVERSA (generic function with 1 method)

In [11]:
matriz1 = [1.0 2.0 3.0; 0.0 4.0 5.0; 1.0 0.0 6.0]
matriz2 = [2.0 1.0 0.0; 0.0 1.0 0.0; 1.0 2.0 1.0]
matriz3 = [1.0 -2.0 5.0; 0.0 1.0 -4.0; 0.0 0.0 1.0]

print("Inversa 1: ")
print(INVERSA(matriz1))
print("\n\n")
print("Inversa 2: ")
print(INVERSA(matriz2))
print("\n\n")
print("Inversa 3: ")
print(INVERSA(matriz3))

Inversa 1: [1.0909090909090908 -0.5454545454545454 -0.09090909090909083; 0.2272727272727273 0.13636363636363635 -0.2272727272727273; -0.18181818181818182 0.09090909090909091 0.18181818181818182]

Inversa 2: [0.5 -0.5 0.0; 0.0 1.0 0.0; -0.5 -1.5 1.0]

Inversa 3: [1.0 2.0 3.0; 0.0 1.0 4.0; 0.0 0.0 1.0]

##### 2)

##### 3)

a)

Para resolver o sistema, é preciso monta-lo da forma que cada variavel x1 x2 x3 x4 seja uma incognita do sistema linear. Partindo do ponto que o valor de uma variavel é a media dos vertices a sua volta. Podemos montar o sistema e com um pouco de algebra obtemos a seguinte matriz:

$$ \begin{bmatrix}
4 & -1 & -1 & 0 \\
-1 & 4 & 0 & -1 \\
-1 & 0 & 4 & -1 \\
0 & -1 & -1 & 4 \\
\end{bmatrix} $$

Com o seguinte vetor de resultado
$$ \begin{bmatrix}
20  \\
50 \\
-15  \\
45 \\
\end{bmatrix} $$



b)

Utilizarei a função de decomposição LU e parte do raciocinio para obter o resultado da função. Temos que y = Ux e que Ly = vetor

In [12]:
matriz = [
  4.0 -1.0 -1.0 0.0;
  -1.0 4.0 0.0 -1.0 ;
  -1.0 0.0 4.0 -1.0 ;
  0.0 -1.0 -1.0 4.0
]

vetor = [
  20.0
  50.0
  -15.0
  45.0
]

L, U = DECOMPOSICAO_LU(matriz)

y = RESOLVE_TRIANNGULAR_INFERIOR(L, vetor)

resultado = RESOLVE_TRIANNGULAR_SUPERIOR(U, y)

# output =
# x1
# x2
# x3
# x4

4-element Vector{Float64}:
 10.625
 19.375
  3.1249999999999987
 16.874999999999996

c) 

In [13]:
function lake(n, up, down, left, right)
  A = zeros(n^2, n^2)
  b = zeros(n^2)
  
  for i = 1:(n^2)
    row = ((i - 1) ÷ n) + 1
    column = ((i - 1) % n) + 1

    A[i,i] = 4.0

    if row == 1
      b[i] += up
    else
      A[i, i - n] = -1.0
    end

    if row == n
      b[i] += down
    else
      A[i, i + n] = -1.0
    end

    if column == 1
      b[i] += left
    else
      A[i, i - 1] = -1.0
    end

    if column == n
      b[i] += right
    else
      A[i, i + 1] = -1.0
    end
  end

  return A, b
end

lake (generic function with 1 method)

In [14]:
A, b = lake(5, 20.0, 30.0, 25.0, 20.0)

L, U = DECOMPOSICAO_LU(A)

y = RESOLVE_TRIANNGULAR_INFERIOR(L, b)

resultado = RESOLVE_TRIANNGULAR_SUPERIOR(U, y)

25-element Vector{Float64}:
 22.656565656565654
 21.762286324786324
 21.28651903651904
 20.89359945609946
 20.46969696969697
 23.863976301476303
 23.106060606060602
 22.49019036519036
 21.818181818181817
 20.98518842268842
 24.69327894327894
 24.30778943278943
 23.75
 22.903749028749036
 21.65287490287491
 25.601350038850036
 25.68181818181818
 25.29827117327117
 24.393939393939394
 22.722562160062164
 27.030303030303024
 27.519862082362078
 27.367327117327115
 26.65117521367521
 24.84343434343434

d)
Sempre é possivel discretizar com mais nós porque o determinante é diferente de 0. Com 100 passa de 2 min.

Benchmark: 

60 = 40s

70 = 1m37s


In [22]:
A, b = lake(70, 20.0, 30.0, 25.0, 20.0)

L, U = DECOMPOSICAO_LU(A)

y = RESOLVE_TRIANNGULAR_INFERIOR(L, b)

resultado = RESOLVE_TRIANNGULAR_SUPERIOR(U, y)

4900-element Vector{Float64}:
 22.50108558998749
 21.513904439159596
 21.050189812773926
 20.796787746162533
 20.64099532459102
 20.536553881170132
 20.461993092073193
 20.40623259644159
 20.363034297521292
 20.328632293894486
 20.30062227421697
 20.277398042777357
 20.257845850530398
  ⋮
 29.45633632835899
 29.409238166074058
 29.35249628969431
 29.28290470185692
 29.195661213527046
 29.08324049474785
 28.93317286263133
 28.723304141337515
 28.410700260980292
 27.90285049330702
 26.97435563736066
 24.99891441001252

##### 4)